swiftmailer:
    url: '%env(MAILER_URL)%'
    sender_address: 'admim@alpha-hydro.com'
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false