framework:
    translator:
        enabled: false
#    default_locale: '%locale%'
#    translator:
#        paths:
#            - '%kernel.project_dir%/translations'
#        fallbacks:
#            - '%locale%'
