#index:
#    path: /
#    controller: App\Controller\DefaultController::index

about:
    path: /about
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: base/static/about.html.twig

contacts:
    path: /contacts
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: base/static/contacts.html.twig

logout:
    path: /logout