<?php declare(strict_types = 1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180327134912 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649B8C2FD88');
        $this->addSql('ALTER TABLE wf_category DROP FOREIGN KEY fk_category_category');
        $this->addSql('ALTER TABLE wf_category_properties DROP FOREIGN KEY fk_category_properties_category1');
        $this->addSql('ALTER TABLE wf_product DROP FOREIGN KEY fk_product_category1');
        $this->addSql('ALTER TABLE wf_product DROP FOREIGN KEY fk_product_product_construction1');
        $this->addSql('ALTER TABLE wf_product DROP FOREIGN KEY fk_product_product_control1');
        $this->addSql('ALTER TABLE wf_product DROP FOREIGN KEY fk_product_product_size1');
        $this->addSql('ALTER TABLE wf_product DROP FOREIGN KEY fk_product_product_type1');
        $this->addSql('DROP TABLE categories_xref');
        $this->addSql('DROP TABLE categoryIndex');
        $this->addSql('DROP TABLE forum');
        $this->addSql('DROP TABLE manufacture');
        $this->addSql('DROP TABLE manufacture_categories');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE media_categories');
        $this->addSql('DROP TABLE oil');
        $this->addSql('DROP TABLE oil_categories');
        $this->addSql('DROP TABLE pages');
        $this->addSql('DROP TABLE pipeline');
        $this->addSql('DROP TABLE pipeline_categories');
        $this->addSql('DROP TABLE pipeline_property');
        $this->addSql('DROP TABLE pipeline_property_values');
        $this->addSql('DROP TABLE productIndex');
        $this->addSql('DROP TABLE product_params');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE subproduct_params');
        $this->addSql('DROP TABLE subproduct_params_values');
        $this->addSql('DROP TABLE subproducts');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE wf_category');
        $this->addSql('DROP TABLE wf_category_properties');
        $this->addSql('DROP TABLE wf_product');
        $this->addSql('DROP TABLE wf_product_construction');
        $this->addSql('DROP TABLE wf_product_control');
        $this->addSql('DROP TABLE wf_product_size');
        $this->addSql('DROP TABLE wf_product_type');
        $this->addSql('ALTER TABLE categories DROP add_date, DROP mod_date, DROP generate, DROP meta_description, DROP meta_keywords, DROP meta_title, DROP content_markdown, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE full_path full_path VARCHAR(255) NOT NULL, CHANGE path path VARCHAR(255) NOT NULL, CHANGE upload_path upload_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668727ACA70 FOREIGN KEY (parent_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE categories RENAME INDEX fk_categories_categories_idx TO IDX_3AF34668727ACA70');
        $this->addSql('DROP INDEX `order` ON products');
        $this->addSql('DROP INDEX product_id ON products');
        $this->addSql('DROP INDEX s_name ON products');
        $this->addSql('DROP INDEX sku ON products');
        $this->addSql('ALTER TABLE products DROP parent_id, DROP a_images, DROP note, DROP add_date, DROP mod_date, DROP `order`, DROP meta_description, DROP meta_keywords, DROP meta_title, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE category_id category_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE s_name s_name LONGTEXT DEFAULT NULL, CHANGE full_path full_path VARCHAR(255) NOT NULL, CHANGE path path VARCHAR(255) NOT NULL, CHANGE sorting sorting INT NOT NULL, CHANGE deleted deleted TINYINT(1) NOT NULL, CHANGE upload_path upload_path VARCHAR(255) DEFAULT NULL, CHANGE upload_path_draft upload_path_draft VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE products RENAME INDEX category_id TO IDX_B3BA5A5A12469DE2');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE categories_xref (product_id BIGINT NOT NULL, category_id BIGINT NOT NULL, PRIMARY KEY(product_id, category_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE categoryIndex (id BIGINT AUTO_INCREMENT NOT NULL, category_id BIGINT NOT NULL, page BIGINT NOT NULL, depth TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE forum (id BIGINT AUTO_INCREMENT NOT NULL, parent_id BIGINT DEFAULT NULL, category TEXT DEFAULT NULL COLLATE utf8_general_ci, author VARCHAR(255) NOT NULL COLLATE utf8_general_ci, email VARCHAR(255) NOT NULL COLLATE utf8_general_ci, content LONGTEXT NOT NULL COLLATE utf8_general_ci, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, active INT DEFAULT 1 NOT NULL, deleted INT DEFAULT 0 NOT NULL, content_markdown LONGTEXT DEFAULT NULL COLLATE utf8_general_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manufacture (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT 0 NOT NULL, title VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, path VARCHAR(128) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, description TEXT DEFAULT NULL COLLATE utf8_general_ci, content_html TEXT DEFAULT NULL COLLATE utf8_general_ci, content_markdown LONGTEXT DEFAULT NULL COLLATE utf8_general_ci, image VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, create_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, active TINYINT(1) DEFAULT \'1\' NOT NULL, sorting INT DEFAULT 0 NOT NULL, deleted TINYINT(1) DEFAULT \'0\' NOT NULL, full_path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, UNIQUE INDEX unique_id (id), UNIQUE INDEX unique_full_path (full_path), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manufacture_categories (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT 0 NOT NULL, title VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, path VARCHAR(128) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, description TEXT DEFAULT NULL COLLATE utf8_general_ci, content_html TEXT DEFAULT NULL COLLATE utf8_general_ci, content_markdown LONGTEXT DEFAULT NULL COLLATE utf8_general_ci, image VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, create_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, active TINYINT(1) DEFAULT \'1\' NOT NULL, sorting INT DEFAULT 0 NOT NULL, deleted TINYINT(1) DEFAULT \'0\' NOT NULL, UNIQUE INDEX unique_id (id), UNIQUE INDEX unique_path (path), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media (id BIGINT AUTO_INCREMENT NOT NULL, category_id BIGINT DEFAULT NULL, name TEXT NOT NULL COLLATE utf8_general_ci, s_content MEDIUMTEXT DEFAULT NULL COLLATE utf8_general_ci, content LONGTEXT NOT NULL COLLATE utf8_general_ci, author VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, image VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, full_path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, content_markdown TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords TEXT DEFAULT NULL COLLATE utf8_general_ci, sorting INT DEFAULT 0 NOT NULL, active INT DEFAULT 1 NOT NULL, deleted INT DEFAULT 0 NOT NULL, section_site_id INT DEFAULT 0 NOT NULL, thumb VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, content_html TEXT DEFAULT NULL COLLATE utf8_general_ci, UNIQUE INDEX unique_id (id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media_categories (id BIGINT AUTO_INCREMENT NOT NULL, parent_id BIGINT DEFAULT NULL, name TEXT NOT NULL COLLATE utf8_general_ci, description LONGTEXT NOT NULL COLLATE utf8_general_ci, image VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords TEXT DEFAULT NULL COLLATE utf8_general_ci, sorting INT DEFAULT 0 NOT NULL, active INT DEFAULT 1 NOT NULL, deleted INT DEFAULT 0 NOT NULL, thumb VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, UNIQUE INDEX unique_id (id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oil (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT 0 NOT NULL, title VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, path VARCHAR(128) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, description TEXT DEFAULT NULL COLLATE utf8_general_ci, content_html TEXT DEFAULT NULL COLLATE utf8_general_ci, content_markdown TEXT DEFAULT NULL COLLATE utf8_general_ci, image VARCHAR(128) DEFAULT NULL COLLATE utf8_general_ci, date_create DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, active TINYINT(1) DEFAULT \'1\' NOT NULL, sorting INT DEFAULT 0 NOT NULL, deleted TINYINT(1) DEFAULT \'0\' NOT NULL, full_path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, UNIQUE INDEX unique_id (id), UNIQUE INDEX oil_full_path_uindex (full_path), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oil_categories (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT 0 NOT NULL, title VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, full_path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, description TEXT DEFAULT NULL COLLATE utf8_general_ci, content_html TEXT DEFAULT NULL COLLATE utf8_general_ci, content_markdown TEXT DEFAULT NULL COLLATE utf8_general_ci, image VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, create_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, active INT DEFAULT 1 NOT NULL, sorting INT DEFAULT 0 NOT NULL, deleted INT DEFAULT 0 NOT NULL, UNIQUE INDEX oil_categories_id_uindex (id), UNIQUE INDEX oil_categories_full_path_uindex (full_path), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pages (id INT AUTO_INCREMENT NOT NULL, path VARCHAR(128) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, title VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, description TEXT DEFAULT NULL COLLATE utf8_general_ci, content_markdown TEXT DEFAULT NULL COLLATE utf8_general_ci, content_html TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords TEXT DEFAULT NULL COLLATE utf8_general_ci, sorting INT DEFAULT 0 NOT NULL, active INT DEFAULT 1 NOT NULL, deleted INT DEFAULT 0 NOT NULL, image VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, date_create DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX unique_id (id), UNIQUE INDEX unique_path (path), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pipeline (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT 0 NOT NULL, path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, full_path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, title VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, description TEXT DEFAULT NULL COLLATE utf8_general_ci, content_html TEXT DEFAULT NULL COLLATE utf8_general_ci, content_markdown TEXT DEFAULT NULL COLLATE utf8_general_ci, image VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, create_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, active INT DEFAULT 1 NOT NULL, sorting INT DEFAULT 0 NOT NULL, deleted INT DEFAULT 0 NOT NULL, image_draft VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, image_table VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, gost_name VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, UNIQUE INDEX unique_id (id), UNIQUE INDEX unique_full_path (full_path), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pipeline_categories (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT 0 NOT NULL, path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, full_path VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, title VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, description TEXT DEFAULT NULL COLLATE utf8_general_ci, content_html TEXT DEFAULT NULL COLLATE utf8_general_ci, content_markdown TEXT DEFAULT NULL COLLATE utf8_general_ci, image VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, create_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, active INT DEFAULT 1 NOT NULL, sorting INT DEFAULT 0 NOT NULL, deleted INT DEFAULT 0 NOT NULL, UNIQUE INDEX unique_id (id), UNIQUE INDEX unique_full_path (full_path), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pipeline_property (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, sorting INT DEFAULT 0 NOT NULL, show_list INT DEFAULT 1 NOT NULL, active INT DEFAULT 1 NOT NULL, deleted INT DEFAULT 0 NOT NULL, sistem_name VARCHAR(255) DEFAULT \'\' NOT NULL COLLATE utf8_general_ci, type INT DEFAULT 0 NOT NULL, UNIQUE INDEX unique_id (id), UNIQUE INDEX unique_sistem_name (sistem_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pipeline_property_values (id INT AUTO_INCREMENT NOT NULL, property_id INT NOT NULL, pipeline_id INT NOT NULL, value TEXT DEFAULT NULL COLLATE utf8_general_ci, INDEX property_id (property_id), INDEX pipeline_id (pipeline_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE productIndex (id BIGINT AUTO_INCREMENT NOT NULL, product_id BIGINT NOT NULL, page INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_params (id BIGINT AUTO_INCREMENT NOT NULL, product_id BIGINT NOT NULL, name TEXT NOT NULL COLLATE utf8_general_ci, value TEXT NOT NULL COLLATE utf8_general_ci, `order` INT DEFAULT 0 NOT NULL, INDEX product_id (product_id), INDEX `order` (`order`), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(42) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subproduct_params (id BIGINT AUTO_INCREMENT NOT NULL, product_id BIGINT NOT NULL, name TEXT NOT NULL COLLATE utf8_general_ci, `order` INT DEFAULT 0 NOT NULL, INDEX subproduct_id (product_id), INDEX `order` (`order`), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subproduct_params_values (id INT AUTO_INCREMENT NOT NULL, subproduct_id BIGINT NOT NULL, param_id BIGINT NOT NULL, value TEXT NOT NULL COLLATE utf8_general_ci, UNIQUE INDEX subproduct_params_values_id_uindex (id), INDEX subproduct_id (subproduct_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subproducts (id BIGINT AUTO_INCREMENT NOT NULL, parent_id BIGINT DEFAULT NULL, sku VARCHAR(255) NOT NULL COLLATE utf8_general_ci, name TEXT DEFAULT NULL COLLATE utf8_general_ci, add_date DATETIME DEFAULT NULL, mod_date DATETIME DEFAULT NULL, `order` BIGINT DEFAULT NULL, deleted INT DEFAULT 0 NOT NULL, INDEX `order` (`order`), INDEX product_id (parent_id), INDEX sku (sku), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(42) DEFAULT NULL COLLATE utf8_unicode_ci, email VARCHAR(42) NOT NULL COLLATE utf8_unicode_ci, phone VARCHAR(42) DEFAULT NULL COLLATE utf8_unicode_ci, address VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, roleId INT NOT NULL, password VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, status INT NOT NULL, dateCreate DATETIME NOT NULL, pwdResetToken VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, pwdResetTokenCreateDate DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), INDEX IDX_8D93D649B8C2FD88 (roleId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wf_category (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_general_ci, image VARCHAR(128) DEFAULT NULL COLLATE utf8_general_ci, description TEXT DEFAULT NULL COLLATE utf8_general_ci, path VARCHAR(128) NOT NULL COLLATE utf8_general_ci, full_path VARCHAR(128) NOT NULL COLLATE utf8_general_ci, active TINYINT(1) DEFAULT \'1\' NOT NULL, sorting INT DEFAULT 0 NOT NULL, deleted TINYINT(1) DEFAULT \'0\' NOT NULL, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, content_markdown TEXT DEFAULT NULL COLLATE utf8_general_ci, content_html TEXT DEFAULT NULL COLLATE utf8_general_ci, UNIQUE INDEX wf_category_full_path_uindex (full_path), INDEX fk_category_category_idx (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wf_category_properties (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, value TEXT NOT NULL COLLATE utf8_general_ci, INDEX fk_category_properties_category1_idx (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wf_product (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, product_construction_id INT DEFAULT NULL, product_size_id INT DEFAULT NULL, product_type_id INT DEFAULT NULL, product_control_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_general_ci, data_sheet_no VARCHAR(11) NOT NULL COLLATE utf8_general_ci, data_sheet_pdf VARCHAR(45) NOT NULL COLLATE utf8_general_ci, image VARCHAR(128) DEFAULT NULL COLLATE utf8_general_ci, description TEXT DEFAULT NULL COLLATE utf8_general_ci, content_markdown TEXT DEFAULT NULL COLLATE utf8_general_ci, content_html TEXT DEFAULT NULL COLLATE utf8_general_ci, path VARCHAR(128) DEFAULT NULL COLLATE utf8_general_ci, full_path VARCHAR(128) DEFAULT NULL COLLATE utf8_general_ci, active TINYINT(1) DEFAULT \'1\' NOT NULL, deleted TINYINT(1) DEFAULT \'0\' NOT NULL, sorting INT DEFAULT 0 NOT NULL, meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, INDEX fk_product_category1_idx (category_id), INDEX fk_product_product_construction1_idx (product_construction_id), INDEX fk_product_product_size1_idx (product_size_id), INDEX fk_product_product_type1_idx (product_type_id), INDEX fk_product_product_control1_idx (product_control_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wf_product_construction (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_general_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wf_product_control (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_general_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wf_product_size (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(128) NOT NULL COLLATE utf8_general_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wf_product_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(128) NOT NULL COLLATE utf8_general_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649B8C2FD88 FOREIGN KEY (roleId) REFERENCES role (id)');
        $this->addSql('ALTER TABLE wf_category ADD CONSTRAINT fk_category_category FOREIGN KEY (parent_id) REFERENCES wf_category (id)');
        $this->addSql('ALTER TABLE wf_category_properties ADD CONSTRAINT fk_category_properties_category1 FOREIGN KEY (category_id) REFERENCES wf_category (id)');
        $this->addSql('ALTER TABLE wf_product ADD CONSTRAINT fk_product_category1 FOREIGN KEY (category_id) REFERENCES wf_category (id)');
        $this->addSql('ALTER TABLE wf_product ADD CONSTRAINT fk_product_product_construction1 FOREIGN KEY (product_construction_id) REFERENCES wf_product_construction (id)');
        $this->addSql('ALTER TABLE wf_product ADD CONSTRAINT fk_product_product_control1 FOREIGN KEY (product_control_id) REFERENCES wf_product_control (id)');
        $this->addSql('ALTER TABLE wf_product ADD CONSTRAINT fk_product_product_size1 FOREIGN KEY (product_size_id) REFERENCES wf_product_size (id)');
        $this->addSql('ALTER TABLE wf_product ADD CONSTRAINT fk_product_product_type1 FOREIGN KEY (product_type_id) REFERENCES wf_product_type (id)');
        $this->addSql('ALTER TABLE categories DROP FOREIGN KEY FK_3AF34668727ACA70');
        $this->addSql('ALTER TABLE categories ADD add_date DATETIME DEFAULT NULL, ADD mod_date DATETIME DEFAULT NULL, ADD generate INT DEFAULT NULL, ADD meta_description TEXT DEFAULT NULL COLLATE utf8_general_ci, ADD meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, ADD meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, ADD content_markdown TEXT DEFAULT NULL COLLATE utf8_general_ci, CHANGE description description TEXT DEFAULT NULL COLLATE utf8_general_ci, CHANGE full_path full_path VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, CHANGE path path VARCHAR(128) DEFAULT NULL COLLATE utf8_general_ci, CHANGE upload_path upload_path VARCHAR(128) DEFAULT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE categories RENAME INDEX idx_3af34668727aca70 TO fk_categories_categories_idx');
        $this->addSql('ALTER TABLE products DROP FOREIGN KEY FK_B3BA5A5A12469DE2');
        $this->addSql('ALTER TABLE products ADD parent_id TINYINT(1) DEFAULT NULL, ADD a_images TEXT DEFAULT NULL COLLATE utf8_general_ci, ADD note TEXT DEFAULT NULL COLLATE utf8_general_ci, ADD add_date DATETIME DEFAULT NULL, ADD mod_date DATETIME DEFAULT NULL, ADD `order` BIGINT DEFAULT NULL, ADD meta_description LONGTEXT DEFAULT NULL COLLATE utf8_general_ci, ADD meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, ADD meta_title VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE category_id category_id INT NOT NULL, CHANGE name name TEXT DEFAULT NULL COLLATE utf8_general_ci, CHANGE s_name s_name VARCHAR(2028) DEFAULT NULL COLLATE utf8_general_ci, CHANGE upload_path upload_path VARCHAR(128) DEFAULT NULL COLLATE utf8_general_ci, CHANGE upload_path_draft upload_path_draft VARCHAR(128) DEFAULT NULL COLLATE utf8_general_ci, CHANGE full_path full_path VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci, CHANGE path path VARCHAR(128) DEFAULT NULL COLLATE utf8_general_ci, CHANGE deleted deleted INT NOT NULL, CHANGE sorting sorting TINYINT(1) NOT NULL');
        $this->addSql('CREATE INDEX `order` ON products (`order`)');
        $this->addSql('CREATE INDEX product_id ON products (parent_id)');
        $this->addSql('CREATE INDEX s_name ON products (s_name)');
        $this->addSql('CREATE INDEX sku ON products (sku)');
        $this->addSql('ALTER TABLE products RENAME INDEX idx_b3ba5a5a12469de2 TO category_id');
    }
}
